version: 2
updates:
  - package-ecosystem: maven
    directory: "/stebz-parent"
    schedule:
      interval: "cron"
      cronjob: "0 3 * * *"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.stebz:*"
      - dependency-name: "*-plugin"
      - dependency-name: "org.mockito:mockito-core"
      - dependency-name: "org.junit.jupiter:junit-jupiter-api"
      - dependency-name: "org.junit.platform:junit-platform-launcher"
      - dependency-name: "io.qameta.allure:allure-java-commons"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "io.qameta.allure:allure-junit5"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "io.qase:qase-java-commons"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "com.epam.reportportal:client-java"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "ru.testit:testit-java-commons"
        update-types: [ "version-update:semver-patch" ]
