version: 2
updates:
  - package-ecosystem: maven
    directory: "/stebz-parent"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "org.stebz:*"
      - dependency-name: "*-plugin"
      - dependency-name: "org.mockito:mockito-core"
