version: 2
updates:
  - package-ecosystem: maven
    directory: "/stebz-parent"
    schedule:
      interval: "cron"
      cronjob: "0 3 * * *"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.stebz:*"
      - dependency-name: "*-plugin"
      - dependency-name: "org.mockito:mockito-core"
